### ISSUE TITLE
do you know about the inconsistencies?

### ISSUE THREAD

**Issue by fmorton** [adafruit/Adafruit_CircuitPython_IRRemote#17]
Thanks for this. It has been really helpful and I am using it on projects. I added a helper layer on top of this code for the adafruit mini remote control at:

https://github.com/fmorton/Makers_CircuitPython_remote_control

Using it, I have seen a lot of inconsistencies in results. For example, at times, if you press a button, nothing is returned. But, if you press it again, then you get it twice.

Is this something you are aware of? Is it from inconsistencies with the remote itself or do you think their are issues with the irremote code? I'm willing to dig into it, but thought I'd ask you first in case you have already pushed this as far as can be done. Particularly if there are issues with the remote itself.

Thanks!

**Comment by tannewt** [comment]
IR can be pretty inconsistent on its own because its easy to have interference. We haven't worried about it much because most folks are used to having to press it a second time if it fails the first time.

My guess is that you are seeing incorrect detection of the end of a code. I bet you can improve it but that it will always be a bit finicky.

**Comment by kevinjwalters** [comment]
Have a look at the description of issue in #16 to see if it's same problem.

**Comment by fmorton** [comment]
The recent PR fixes this problem. Or, at least adds improvements.
